; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters =
	esp32_exception_decoder
upload_port = /dev/cu.usbmodem101
monitor_port = /dev/cu.usbmodem5A2E0112961
build_flags = 
	-D DEBUG_LEVEL=5
	-D CONFIG_NIMBLE_CPP_LOG_LEVEL=0
	-D NIMBLE_CPP_DEBUG=0
	-DARDUINO_ARCH_ESP32
	-DESP_PLATFORM
	-DUSE_NIMBLE
	-DCONFIG_BT_NIMBLE_ROLE_PERIPHERAL_ONLY
	-DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
	-DCONFIG_BT_NIMBLE_MAX_BONDS=1
	-DCONFIG_BT_NIMBLE_MAX_CCCDS=3
	-DCONFIG_BT_NIMBLE_ATT_PREFERRED_MTU=23
lib_deps = 
	adafruit/Adafruit NeoPixel @ ^1.12.4
	h2zero/NimBLE-Arduino @ ^1.4.1
build_unflags = 
	-DCONFIG_BT_ENABLED
	-DCONFIG_BLUEDROID_ENABLED
